/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author neira
 */
public class frmAgregarProd extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarProd
     */
    public frmAgregarProd() {
        initComponents();
        setSize(600,500);
        setLayout(null);
        setResizable(false);
        
        setTitle("Ventana de productos...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloProducto = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblLoteProductos = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtLoteProducto = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloProducto.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lblTituloProducto.setText("Productos:");
        jPanel1.add(lblTituloProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 200, 50));

        lblIdProducto.setText("Id Producto: ");
        jPanel1.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 30));
        jPanel1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        lblNombreProducto.setText("Nombre Producto:");
        jPanel1.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 20));
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        lblLoteProductos.setText("Lote Productos: ");
        jPanel1.add(lblLoteProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 20));

        lblFecha.setText("Fecha:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, -1));
        jPanel1.add(txtLoteProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblLoteProductos;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblTituloProducto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtLoteProducto;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
