/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Zapallo
 */
public class frmInventario extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmInventario() {
        initComponents();
        setSize(800,700);
        setLayout(null);
        setResizable(false);
        setTitle("Proyecto Inventario..");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlStock = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblAgregar = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JTextField();
        lblDestino = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        lblRetiro = new javax.swing.JLabel();
        cmbRetiro = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNomUsuario = new javax.swing.JLabel();
        txtNomUsuario = new javax.swing.JTextField();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpcion = new javax.swing.JMenu();
        mnuListas = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlStock.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Stock"));
        pnlStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProducto.setText("ID_Producto:");
        pnlStock.add(lblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, -1));
        pnlStock.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, -1));

        lblNombre.setText("Nombre Producto:");
        pnlStock.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));
        pnlStock.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        lblAgregar.setText("Agregar Producto:");
        pnlStock.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 140, -1));
        pnlStock.add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 50, -1));

        lblDestino.setText("Bodega de destino:");
        pnlStock.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 120, -1));

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temuco", "Lautaro", "Santiago", "Iquique", "Labranza", "Pucon" }));
        pnlStock.add(cmbDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 140, -1));

        lblRetiro.setText("Retiro en tienda:");
        pnlStock.add(lblRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        cmbRetiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lautaro", "Temuco" }));
        pnlStock.add(cmbRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 20));

        btnGuardar.setText("Guardar");
        pnlStock.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 120, -1));

        btnEliminar.setText("Eliminar");
        pnlStock.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 120, -1));

        jPanel1.add(pnlStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 660, 220));

        pnlFondo.setBackground(new java.awt.Color(0, 153, 153));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        lblTitulo.setText("Registro de inventario:");
        pnlFondo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 390, 80));

        jPanel1.add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomUsuario.setText("Nombre usuario:");
        jPanel2.add(lblNomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));
        jPanel2.add(txtNomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        lblRut.setText("Rut:");
        jPanel2.add(lblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));
        jPanel2.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, -1));

        lblFecha.setText("Fecha Ingreso:");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, -1));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, -1));

        lblCargo.setText("Cargo:");
        jPanel2.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 120, -1));
        jPanel2.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 660, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 730));

        mnuOpcion.setText("Opciones");

        mnuListas.setText("Listado de Productos");
        mnuOpcion.add(mnuListas);

        mnuSalir.setText("Salir");
        mnuOpcion.add(mnuSalir);

        jMenuBar1.add(mnuOpcion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbRetiro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNomUsuario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblRetiro;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuListas;
    private javax.swing.JMenu mnuOpcion;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlStock;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNomUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
