/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.Conexion;
import dto.UsuariosDto;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author neira
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        setSize(700,600);
        setResizable(false);
        setLayout(null);
        
        setTitle("Ventana Menu..");
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloMenu = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblActividad = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnListaProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtActividad = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloMenu.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        lblTituloMenu.setText("\"Bienvenido al Inventario\"");
        jPanel1.add(lblTituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 450, 50));

        lblNombreUsu.setText("Nombre Usuario:");
        jPanel1.add(lblNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblRol.setText("Rol:");
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, -1));

        lblActividad.setText("Actividad:");
        jPanel1.add(lblActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnCerrarSesion.setText("Cerrar sesion.");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 180, 50));

        btnListaProducto.setText("Lista de Productos.");
        jPanel1.add(btnListaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 180, 50));

        btnAgregarProducto.setText("Agregar Producto.");
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
        });
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 180, 50));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));
        jPanel1.add(txtActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, -1));
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 690, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        frmAgregarProd objAgregarProd = new frmAgregarProd();
            objAgregarProd.setVisible(true);
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        List<UsuariosDto> listaUsuarios = new ArrayList<>();

        try {
            Conexion objConexion = new Conexion();
            Statement datosUsuario = objConexion.establecerConexion().createStatement();
            ResultSet dtoUser = datosUsuario.executeQuery("SELECT usu_usuarios FROM usuarios ;");

            while (dtoUser.next()) {

                UsuariosDto usr = new UsuariosDto();
                usr.setUsuario(dtoUser.getString("usu_usuario"));
                 listaUsuarios.add(usr);

            }
            dtoUser.close();
            datosUsuario.close();
            objConexion.cerrarConexion();

        } catch (Exception e) {
        }        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnListaProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTituloMenu;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
