/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author neira
 */
public class frmQuitar extends javax.swing.JFrame {

    /**
     * Creates new form frmQuitar
     */
    public frmQuitar() {
        initComponents();
        setSize(600, 500);
        setLayout(null);
        setResizable(false);
        setLocationRelativeTo(null);

        setTitle("ventana quitar...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloQuitar = new javax.swing.JLabel();
        pnlDetalle = new javax.swing.JPanel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidadProd = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotalProd = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        lblIdProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblLoteProductos = new javax.swing.JLabel();
        txtLoteProducto = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        btnQuitarBd = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloQuitar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblTituloQuitar.setText("Quitar Producto: ");
        jPanel1.add(lblTituloQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 300, 60));

        pnlDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de producto"));
        pnlDetalle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCantidad.setText("Cantidad:");
        pnlDetalle.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 30));
        pnlDetalle.add(txtCantidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 100, -1));

        lblTotal.setText("Total en bodega:");
        pnlDetalle.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, 30));
        pnlDetalle.add(txtTotalProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));
        pnlDetalle.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));
        pnlDetalle.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, -1));

        lblIdProducto.setText("Id Producto: ");
        pnlDetalle.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        lblNombreProducto.setText("Nombre Producto:");
        pnlDetalle.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 20));

        lblLoteProductos.setText("Lote Productos: ");
        pnlDetalle.add(lblLoteProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));
        pnlDetalle.add(txtLoteProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, -1));
        pnlDetalle.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, -1));

        lblFecha.setText("Fecha:");
        pnlDetalle.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 80, -1));

        jPanel1.add(pnlDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 540, 250));

        btnQuitarBd.setText("Quitar producto");
        btnQuitarBd.setToolTipText("");
        jPanel1.add(btnQuitarBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 140, 40));

        btnVolver.setText("Volver al Menu");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmMenu objMenu = new frmMenu();
        objMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitarBd;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblLoteProductos;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblTituloQuitar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTextField txtCantidadProd;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtLoteProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtTotalProd;
    // End of variables declaration//GEN-END:variables
}
